### ISSUE TITLE
v1 Performance Improvements

### ISSUE THREAD

**Issue by jjcomer** [danlentz/clj-uuid#12]
I started to do a little profiling. Our v1 implementation is pretty slow: ~9.4sec to gen 1000000 (vs 2.2 for v4).
Upon inspection it looks like we are spending most of our time casting from clojure numbers to primitives. We may want to look into using prismatic's [hiphip](https://github.com/Prismatic/hiphip) and use primitive arrays and numbers when building the uuid.

**Comment by danlentz** [comment]
hiphip might be a good idea i will look at with interest.  In terms of lower-hanging fruit, though, I was able to improve performance of v1 uuid generation by about 60% by rewriting `assemble-bytes` in bitmop.

*before:*

    clj-uuid> (criterium.core/bench (v1))
    
    Evaluation count : 15909120 in 60 samples of 265152 calls.
    Execution time mean : 3.800846 µs
    Execution time std-deviation : 160.177320 ns
    Execution time lower quantile : 3.614029 µs ( 2.5%)
    Execution time upper quantile : 4.258304 µs (97.5%)
    Overhead used : 1.885558 ns

    Found 4 outliers in 60 samples (6.6667 %)
	low-severe	 2 (3.3333 %)
	low-mild	 2 (3.3333 %)
    Variance from outliers : 28.6803 % Variance is moderately inflated by outliers

*after:*

    clj-uuid> (criterium.core/bench (v1))
    
    Evaluation count : 41142600 in 60 samples of 685710 calls.
    Execution time mean : 1.499075 µs
    Execution time std-deviation : 75.839735 ns
    Execution time lower quantile : 1.423851 µs ( 2.5%)
    Execution time upper quantile : 1.699182 µs (97.5%)
    Overhead used : 1.885558 ns

    Found 9 outliers in 60 samples (15.0000 %)
	low-severe	 5 (8.3333 %)
	low-mild	 4 (6.6667 %)
    Variance from outliers : 36.8382 % Variance is moderately inflated by outliers

**Comment by danlentz** [comment]
also, i think at this point we can generate v1 UUID's more quickly than the JVM's built-in v4.  a quick v4 bench for comparison:

    clj-uuid> (criterium/bench (v4))

    Evaluation count : 31754100 in 60 samples of 529235 calls.
    Execution time mean : 1.928087 µs
    Execution time std-deviation : 100.020001 ns
    Execution time lower quantile : 1.845279 µs ( 2.5%)
    Execution time upper quantile : 2.239196 µs (97.5%)
    Overhead used : 1.885558 ns

    Found 8 outliers in 60 samples (13.3333 %)
	low-severe	 3 (5.0000 %)
	low-mild	 5 (8.3333 %)
    Variance from outliers : 38.4517 % Variance is moderately inflated by outliers

**Comment by jjcomer** [comment]
Awesome! This is a great improvement :+1:

**Comment by danlentz** [comment]
Yep, tks.  I definitely will still look at other ideas like hiphip too but I want to get test suite in order first so that is likely what I will hit next.
