### ISSUE TITLE
Release non-SNAPSHOT version

### ISSUE THREAD

**Issue by bobby** [danlentz/clj-uuid#23]
Hi @danlentz!

Thank you for this library, it's been a performance boost to my application.

Would you consider releasing a non-SNAPSHOT version to Clojars?  SNAPSHOTs tend to do funny and inefficient things during dependency resolution, in my experience.

Also, as a side note: you can include the following code in the README to display a nice link to the latest Clojars dependency info:

```
[![Clojars Project](http://clojars.org/danlentz/clj-uuid/latest-version.svg)](http://clojars.org/danlentz/clj-uuid)
```

Cheers,
Bobby

**Comment by danlentz** [comment]
It's really gratifying to hear that clj-uuid is useful to you!  I have updated the readme with your (improved) clojars link.

Regarding a non-snapshot release -- I agree, I would like to do this.  So far I've been confounded by the procedure to "promote" to non-snapshot on clojars.  I will take another look, though.

**Comment by cloojure** [comment]
I believe all you need to do is create a new version number (e.g. 0.1.23)
without the "-SNAPSHOT" suffix.  Then upload the new one.
Alan

**Comment by jeroenvandijk** [comment]
Hi @danlentz,

Thanks indeed for this library. I would appreciate a non-SNAPSHOT version as well. SNAPSHOT version  s are most painful when you least expect it. They also slow down the lein boot process in case you are not convinced :)

For now I'm using the locked version to the(?) 0.1.2-SNAPSHOT version `[danlentz/clj-uuid "0.1.2-20150217.010720-1"]` 

Cheers, Jeroen

**Comment by danlentz** [comment]
done.
