### ISSUE TITLE
uuid? is always false on strings?

### ISSUE THREAD

**Issue by timvisher** [danlentz/clj-uuid#27]
This surprised me:

```
> (uuid/uuid? (uuid/to-string (uuid/v4)))
false
```

It looks like `String` has `UUIDable` extended to it which would lead me to believe that the above should silently coerce the string to a uuid instance and then report true (or throw an exception or perhaps most preferably simply return false if a UUID instance couldn't be created based on that string).

Is this the intended behavior?

**Comment by danlentz** [comment]
Well, the behavior of silently coercing things seemed to lead to dark places.  As implemented,

```
  (uuid?                         [x]
    "Return `true` if `x` implements an RFC4122 unique identifier.")
```

This would be true currently only for java.util.UUID, although the intent was to allow the protocol open to extend some other UUID representation.  String (and other) coersions are implemented with the UUIDable protocol:

```
(defprotocol UUIDable
  "A UUIDable object directly represents a UUID.  Examples of things which
  might be conceptually 'uuidable' include string representation of a
  UUID in canonical hex format, or an appropriate URN URI."
  
  (as-uuid   ^java.util.UUID [x]
    "Coerce the value 'x' to a UUID.")
  
  (uuidable?                 [x]
    "Return 'true' if 'x' can be coerced to UUID."))
```

So `(uuid? (as-uuid (to-string (v4))))` would be true.  I'm reluctant to go back down the road of silent, best-effort coersions, but if you think there is a more sensible approach than this I'm open to other ideas.

**Comment by timvisher** [comment]
I was unaware that uuidable? actually verified that the string could be turned all the way into a uuid. That suits my needs just fine.
