### ISSUE TITLE
We need an option to disable/make node-id optional

### ISSUE THREAD

**Issue by Phoenix1708** [danlentz/clj-uuid#31]
[This](https://github.com/danlentz/clj-uuid/blob/master/src/clj_uuid/node.clj#L143) will be executed everytime it is loaded. Have you thought about that the [InetAddress/getLocalHost](https://github.com/danlentz/clj-uuid/blob/master/src/clj_uuid/node.clj#L109) is [platform dependent](http://stackoverflow.com/a/7389217/731894) ? In some OS it will do DNS lookup even it is not necessary and throw exception when it can't resolve an internal IP, when the mahine is runs on only has internal IP.

**Comment by aleksandersumowski** [comment]
I'm affected as well: one of the environments when this behaviour gets exposed is AWS Lambda.

**Comment by metametadata** [comment]
Reproducible  on MacOS host when I try to compile my project inside the Docker container ran with `--network=host` option (using `openjdk:8u141-jre` image).

**Comment by dco-lentz** [comment]
Resolved by https://github.com/danlentz/clj-uuid/pull/40
