### ISSUE TITLE
Suggestion: extend nil with UUIDable protocol

### ISSUE THREAD

**Issue by yonatane** [danlentz/clj-uuid#35]
It might be a matter of style, but I'd find it useful if clj-uuid extends nil as UUIDable, with uuidable? returning false and as-uuid throwing.
Regarding as-uuid, could be nice if it returned nil instead of throwing, but I guess it's again a matter of style and also it's a breaking change.
If it sounds reasonable I can submit a PR.

**Comment by dcj** [comment]
+1 on @yonatane 's proposal that (uuidable? nil) -> false

I guess I don't support his proposal that (as-uuid nil) -> nil, my thinking is that if you care, you are trying to turn things you don't know what they are into uuids, then test for uuidable before proceeding.

**Comment by dco-lentz** [comment]
I'm not sure that it makes sense for the return value of `as-uuid` to return anything other than a UUID, which nil is not.  It could be possibly defined that `(as-uuid nil)` could return `uuid/+null+` by convention, although i'm thinking that looser behavior might also have its detractors.
