### ISSUE TITLE
Node ID embedded in AOT-compiled code

### ISSUE THREAD

**Issue by stuartsierra** [danlentz/clj-uuid#37]
When clj-uuid is AOT-compiled, the v1 node ID is fixed at compile time. For example, if clj-uuid is used in an application which is AOT-compiled once and then deployed to multiple machines, it will produce the same v1 node ID on all machines.

This is caused by the `:const` declaration on `clj-uuid.node/+node-id+` and `clj-uuid.node/+v1-lsb+`. During compilation, a `:const` Var is evaluated once and its value embedded in compiled code at the point where it is used.

**Comment by ianbishop** [comment]
@danlentz Can you take a look at why the travis build is failing?

This PR & tests work locally for me but `lein test` seems to fail for travis.

This issue has led to a bunch of our services sharing node-ids & collisions in prod. We're going to need to use a self-hosted version until it's addressed :(.

**Comment by dco-lentz** [comment]
ok. yup thanks for the heads up I hadn't been checking.  Let me have a look
