### ISSUE TITLE
clj-uuid/v5 uuids inconsistent after Clojure 1.11.0

### ISSUE THREAD

**Issue by mbragg02** [danlentz/clj-uuid#51]
Hi, i’ve come across the following when updating to Clojure 1.11.0. In our application we have some places where we create V5  uuids and after the upgrade these uuids are different. An example being:
```
def ^:const +namespace+ #uuid "50d94d91-a1cf-422d-9586-4ddacf6df176")

(clj-uuid/v5 +namespace+ :some-keyword) 

;; Clojure 1.10
=> #uuid "d30e9c3c-ced2-534e-a6b8-ecf784fb0785"

;; Clojure 1.11
=> #uuid "a16f6719-952a-55b9-b71b-b15dd263665b"
```
After some trial an error It seems it is the local part argument i.e :some-keyword that is causing the difference, as the `.writeObject` called on the Keyword object and then converted to a ByteArray, which now appears to be different. https://github.com/danlentz/clj-uuid/blob/master/src/clj_uuid.clj#L565
If I use a String instead of a keyword for the local part argument then the uuid produced is consistent before and after the Clojure upgrade.

Alex Miller has confirmed on my [question on ask.clojure.org](https://ask.clojure.org/index.php/11658/clj-uuid-v5-uuids-inconsistent-after-clojure-1-11-0) that Clojure 1.11.0 made some small/backwards compatible changes to the Keyword class, which results in different binary serialisation. 

The uuids produced by our application are used in downstream systems and It would be quite difficult to have them handle the change. Is there anyway that I could achieve the exact same previous uuids from cli-uuid/v5?

**Comment by dco-lentz** [comment]
Fixed with Clojure 1.11.1 described https://ask.clojure.org/index.php/11658/clj-uuid-v5-uuids-inconsistent-after-clojure-1-11-0
