### ISSUE TITLE
deps and single segment namespace

### ISSUE THREAD

**Issue by Hendekagon** [danlentz/clj-uuid#58]
Please could you add a `deps.edn` and prefix the `clj-uuid` namespace because single segment namespaces cause warnings and are incompatible with GraalVM

**Comment by dco-lentz** [comment]
sure thing I added deps.edn as a todo to https://github.com/danlentz/clj-uuid/issues/57 

As far as single segment namespace -- I'd be concerned to just break backward compatibility do you have an example of an existing single-segment-name project that has accommodated GraalVM in a clean way?

**Comment by Hendekagon** [comment]
hi, thanks. The problem with SSNs is described [here](https://github.com/clj-easy/graal-build-time?tab=readme-ov-file#single-segment-namespaces), perhaps for backwards compatibility the approach taken [here](https://github.com/clj-commons/primitive-math/blob/a4ce3cb3effbffd2039880a3ed905af60b5cf153/src/primitive_math.clj#L3) would work

**Comment by dco-lentz** [comment]
Ok, I've deprecated the single-segment `clj-uuid` namespace and transitioned this to `clj-uuid.core` over on 0.2.1-SNAPSHOT branch https://github.com/danlentz/clj-uuid/pull/56.  Please let me know how this works for you.

**Comment by dco-lentz** [comment]
Incorporated `deps.edn` and transitioned `clj-uuid` -> `clj-uuid.core` and deployed as clj-uuid 0.2.1-SNAPSNOT as part of ongoing work toward 0.2.1 release PR  https://github.com/danlentz/clj-uuid/pull/56

Lets move discussion over to that branch or the associated Issue https://github.com/danlentz/clj-uuid/issues/57
